# Generated by Django 5.2.2 on 2025-06-04 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=50)),
                ('fee', models.CharField(max_length=20)),
                ('fee_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('event_type', models.CharField(choices=[('technical', 'Technical'), ('non-technical', 'Non-Technical')], max_length=20)),
                ('day', models.IntegerField(choices=[(1, 'Day 1'), (2, 'Day 2')])),
                ('is_key_event', models.BooleanField(default=False)),
                ('max_participants', models.IntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
